name: Publish Release

on:
  workflow_dispatch:
    inputs:
      semverType:
        description: 'Which type of semver to release'
        required: true
        type: choice
        options:
          - 'prerelease' # For development releases (e.g. 1.0.0-next.1)
          - 'patch' # For bug fixes (e.g. 1.0.1)
          - 'minor' # For new features (e.g. 1.1.0)
          - 'major' # For breaking changes (e.g. 2.0.0)

jobs:
  # This job extracts all workspace packages from package.json
  # and prepares them for the matrix strategy in the publish job
  read-workspaces:
    runs-on: ubuntu-latest
    outputs:
      # This output will be consumed by the publish job's matrix
      packages: ${{ steps.read-workspaces.outputs.packages }}

    # Enforce branch rules:
    # 1. Only run prerelease versions on the next branch
    # 2. Only run production versions (patch/minor/major) on the main branch
    if: (github.ref == 'refs/heads/main' && github.event.inputs.semverType != 'prerelease') || (github.ref == 'refs/heads/next' && github.event.inputs.semverType == 'prerelease')

    steps:
      # Get the code from the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the built-in token for GitHub Actions

      # Extract workspace package patterns from package.json
      # Note: This only extracts the patterns (e.g. "packages/*"), not the resolved directories
      # The matrix will receive these patterns and each job will process one pattern
      - name: Extract workspaces from package.json
        id: read-workspaces
        run: |
          # Use Node.js to read the workspaces array from package.json
          PACKAGES=$(node -e '
            const pkg = JSON.parse(require("fs").readFileSync("./package.json", "utf8"));
            console.log(JSON.stringify(pkg.workspaces));
          ')
          echo "Found packages: $PACKAGES"
          # Set the output for use in the matrix strategy
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  # Once the packages have been published we create the releases on GitHub
  # No need to use a patched version of please-release here as the version
  # numbers were already incremented in the prepare-release action
  publish-gh-releases:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Using GITHUB_TOKEN makes actions run as github-actions bot

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Publish the GitHub releases
      - name: Release Please
        run: |
          CONFIG_FILE=release/release-please-config.${{ github.event.inputs.semverType }}.json
          MANIFEST_FILE=release/release-please-manifest.${{ github.event.inputs.semverType == 'prerelease' && 'prerelease' || 'prod' }}.json
          echo "Config File: ${CONFIG_FILE}"
          echo "Manifest File: ${MANIFEST_FILE}"
          echo "Repo: ${{ github.repository }}"
          echo "Target Branch: ${{ github.ref_name}}"
          npx --yes release-please github-release --config-file=${CONFIG_FILE} --manifest-file=${MANIFEST_FILE} --repo-url=${{ github.repository }} --target-branch=${{ github.ref_name}} --token=${{ secrets.GITHUB_TOKEN }}
